import BackspaceIcon from "../assets/BackspaceIcon.svg";
import ShiftIcon from "../assets/ShiftIcon.svg";

export const numericButtons = [
  { label: "7", value: "7" },
  { label: "8", value: "8" },
  { label: "9", value: "9" },
  { label: "÷", value: "/" },
  { label: "4", value: "4" },
  { label: "5", value: "5" },
  { label: "6", value: "6" },
  { label: "×", value: "*" },
  { label: "1", value: "1" },
  { label: "2", value: "2" },
  { label: "3", value: "3" },
  { label: "−", value: "-" },
  { label: "0", value: "0" },
  { label: ".", value: "." },
  { label: "=", value: "=" },
  { label: "+", value: "+" },
  // { label: "Clear", value: "" },
];

export const alphabeticButtons = [
  { label: "q", value: "q" },
  { label: "w", value: "w" },
  { label: "e", value: "e" },
  { label: "r", value: "r" },
  { label: "t", value: "t" },
  { label: "y", value: "y" },
  { label: "u", value: "u" },
  { label: "i", value: "i" },
  { label: "o", value: "o" },
  { label: "p", value: "p" },
  { label: "a", value: "a" },
  { label: "s", value: "s" },
  { label: "d", value: "d" },
  { label: "f", value: "f" },
  { label: "g", value: "g" },
  { label: "h", value: "h" },
  { label: "j", value: "j" },
  { label: "k", value: "k" },
  { label: "l", value: "l" },
  // { label: "θ", value: "θ" },
  { label: "z", value: "z" },
  { label: "x", value: "x" },
  { label: "c", value: "c" },
  { label: "v", value: "v" },
  { label: "b", value: "b" },
  { label: "n", value: "n" },
  { label: "m", value: "m" },
  // { label: "Shift", value: "Shift" },
  // { label: "123", value: "123" },
  // { label: "aᵦ", value: "aᵦ" },
  // { label: "!", value: "!" },
  // { label: "%", value: "%" },
  // { label: "[", value: "[" },
  // { label: "]", value: "]" },
  // { label: "{", value: "{" },
  // { label: "}", value: "}" },
  // { label: "~", value: "~" },
  // { label: ",", value: "," },
  { label: "Backspace", value: "Backspace", icon: BackspaceIcon },
  { label: "Enter", value: "Enter" },
  { label: "Shift", value: "Shift", icon: ShiftIcon },
];
